let
  dependencies = import ./dependencies.nix { };
in
with dependencies;
with pkgs;
pkgs.mkShell {
  name = "mastan-check";

  packages = [
    androidSdk
    gradle
    jdk
  ];

  JAVA_HOME = "${jdk}";
  ANDROID_HOME = "${androidSdkHome}";

  # Ensures that we don't have to use a FHS env by using the nix store's aapt2.
  GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${androidSdkHome}/build-tools/${lib.last android.versions.buildTools}/aapt2";

  shellHook = ''
    # Write out local.properties for Android Studio.
    cat <<EOF > local.properties
      # This file was automatically generated by nix-shell.
      sdk.dir=$ANDROID_HOME
    EOF
    # ./gradlew clean check
    # exit 0;
  '';
}
